const CandidateData = [
  {
    id: 1,
    name: "Sarah Johnson",
    photo:"https://i.pravatar.cc/150?img=12",
    initial: "S",
    email: "sarah.johnson@gmail.com",
    jobRole: "AI Engineer",
    experience: "3 Years",
    resume: "Sarah_Johnson_Resume.pdf",
    ats: 91,
    trust: 95,
    fraud: 2,
    plagiarism: 4,
    status: "Verified",
    appliedDate: "24 Jul 2026"
  },
  {
    id: 2,
    name: "Michael Chen",
    photo:"https://i.pravatar.cc/150?img=13",
    initial: "M",
    email: "michael.chen@gmail.com",
    jobRole: "Frontend Developer",
    experience: "2 Years",
    resume: "Michael_Chen_Resume.pdf",
    ats: 87,
    trust: 90,
    fraud: 5,
    plagiarism: 7,
    status: "Verified",
    appliedDate: "24 Jul 2026"
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    photo:"https://i.pravatar.cc/150?img=1",
    initial: "E",
    email: "emily.rodriguez@gmail.com",
    jobRole: "Backend Developer",
    experience: "4 Years",
    resume: "Emily_Rodriguez_Resume.pdf",
    ats: 83,
    trust: 88,
    fraud: 8,
    plagiarism: 10,
    status: "Pending",
    appliedDate: "23 Jul 2026"
  },
  {
    id: 4,
    name: "David Kim",
        photo:"https://i.pravatar.cc/150?img=14",
        initial: "D",
    email: "david.kim@gmail.com",
    jobRole: "Data Scientist",
    experience: "5 Years",
    resume: "David_Kim_Resume.pdf",
    ats: 94,
    trust: 97,
    fraud: 1,
    plagiarism: 3,
    status: "Verified",
    appliedDate: "23 Jul 2026"
  },
  {
    id: 5,
    name: "Jessica Williams",
    initial: "J",
    photo:"https://i.pravatar.cc/150?img=44",
    email: "jessica.williams@gmail.com",
    jobRole: "Full Stack Developer",
    experience: "3 Years",
    resume: "Jessica_Williams_Resume.pdf",
    ats: 80,
    trust: 84,
    fraud: 10,
    plagiarism: 12,
    status: "Rejected",
    appliedDate: "22 Jul 2026"
  },
  {
    id: 6,
    name: "Daniel Wilson",
    photo:"https://i.pravatar.cc/150?img=4",
    initial: "D",
    email: "daniel.wilson@gmail.com",
    jobRole: "Cloud Engineer",
    experience: "6 Years",
    resume: "Daniel_Wilson_Resume.pdf",
    ats: 89,
    trust: 93,
    fraud: 3,
    plagiarism: 5,
    status: "Verified",
    appliedDate: "22 Jul 2026"
  },
  {
    id: 7,
    name: "Sophia Anderson",
    initial: "S",
    photo:"https://i.pravatar.cc/150?img=44",
    email: "sophia.anderson@gmail.com",
    jobRole: "UI/UX Designer",
    experience: "2 Years",
    resume: "Sophia_Anderson_Resume.pdf",
    ats: 78,
    trust: 82,
    fraud: 12,
    plagiarism: 15,
    status: "Pending",
    appliedDate: "21 Jul 2026"
  },
  {
    id: 8,
    name: "Ryan Thomas",
    initial: "R",
    photo:"https://i.pravatar.cc/150?img=12",
    email: "ryan.thomas@gmail.com",
    jobRole: "DevOps Engineer",
    experience: "4 Years",
    resume: "Ryan_Thomas_Resume.pdf",
    ats: 88,
    trust: 91,
    fraud: 4,
    plagiarism: 6,
    status: "Verified",
    appliedDate: "21 Jul 2026"
  },
  {
    id: 9,
    name: "Olivia Martin",
    initial: "O",
    email: "olivia.martin@gmail.com",
    photo:"https://i.pravatar.cc/150?img=11",
    jobRole: "Cyber Security Analyst",
    experience: "5 Years",
    resume: "Olivia_Martin_Resume.pdf",
    ats: 84,
    trust: 86,
    fraud: 9,
    plagiarism: 8,
    status: "Rejected",
    appliedDate: "20 Jul 2026"
  },
  {
    id: 10,
    photo:"https://i.pravatar.cc/150?img=64",
    name: "James Walker",
    initial: "J",
    email: "james.walker@gmail.com",
    jobRole: "Machine Learning Engineer",
    experience: "3 Years",
    resume: "James_Walker_Resume.pdf",
    ats: 92,
    trust: 96,
    fraud: 2,
    plagiarism: 3,
    status: "Verified",
    appliedDate: "20 Jul 2026"
  },
  {
    id: 11,
    photo:"https://i.pravatar.cc/150?img=40",
    name: "Ava Brown",
    initial: "A",
    email: "ava.brown@gmail.com",
    jobRole: "Software Engineer",
    experience: "2 Years",
    resume: "Ava_Brown_Resume.pdf",
    ats: 85,
    trust: 88,
    fraud: 6,
    plagiarism: 7,
    status: "Pending",
    appliedDate: "19 Jul 2026"
  },
  {
    id: 12,
    name: "Ethan Davis",
    initial: "E",
    email: "ethan.davis@gmail.com",
    photo:"https://i.pravatar.cc/150?img=46",
    jobRole: "Python Developer",
    experience: "4 Years",
    resume: "Ethan_Davis_Resume.pdf",
    ats: 90,
    trust: 94,
    fraud: 3,
    plagiarism: 4,
    status: "Verified",
    appliedDate: "19 Jul 2026"
  },
  {
    id: 13,
    name: "Isabella Moore",
    initial: "I",
    photo:"https://i.pravatar.cc/150?img=36",
    email: "isabella.moore@gmail.com",
    jobRole: "React Developer",
    experience: "3 Years",
    resume: "Isabella_Moore_Resume.pdf",
    ats: 82,
    trust: 87,
    fraud: 8,
    plagiarism: 9,
    status: "Rejected",
    appliedDate: "18 Jul 2026"
  },
  {
    id: 14,
    name: "Noah Taylor",
    photo:"https://i.pravatar.cc/150?img=56",
    initial: "N",
    email: "noah.taylor@gmail.com",
    jobRole: "Java Developer",
    experience: "5 Years",
    resume: "Noah_Taylor_Resume.pdf",
    ats: 93,
    trust: 95,
    fraud: 2,
    plagiarism: 2,
    status: "Verified",
    appliedDate: "18 Jul 2026"
  },
  {
    id: 15,
    name: "Mia Garcia",
    photo:"https://i.pravatar.cc/150?img=34",
    initial: "M",
    email: "mia.garcia@gmail.com",
    jobRole: "Database Administrator",
    experience: "4 Years",
    resume: "Mia_Garcia_Resume.pdf",
    ats: 86,
    trust: 89,
    fraud: 5,
    plagiarism: 6,
    status: "Pending",
    appliedDate: "17 Jul 2026"
  }
];

export default CandidateData;